kind: Deployment
apiVersion: apps/v1
metadata:
    name: greeting
spec:
    selector:
        matchLabels:
            app: greeting
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: greeting
        spec:
            containers:
                - name: minikube-greeting-htbhr
                  image: quarkus/minikube_greeting-jvm:latest
                  resources: {}
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  imagePullPolicy: IfNotPresent
                  env:
                      -   name: POSTGRES_HOST
                          value: postgres-greeting
                      -   name: POSTGRES_PORT
                          value: "5432"
                      -   name: POSTGRES_DB
                          valueFrom:
                              configMapKeyRef:
                                  key: POSTGRES_DB
                                  name: postgres-greeting-config
                      -   name: POSTGRES_USER
                          valueFrom:
                              configMapKeyRef:
                                  key: POSTGRES_USER
                                  name: postgres-greeting-config
                      -   name: POSTGRES_PASSWORD
                          valueFrom:
                              secretKeyRef:
                                  key: POSTGRES_PASSWORD
                                  name: postgres-greeting-secret
            restartPolicy: Always
            terminationGracePeriodSeconds: 30
            dnsPolicy: ClusterFirst
            securityContext: {}
            schedulerName: default-scheduler
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 25%
            maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
    name: greeting
spec:
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          nodePort: 32026
    selector:
        app: greeting
    clusterIP: 10.102.111.93
    type: NodePort
    sessionAffinity: None
    externalTrafficPolicy: Cluster
