kind: Deployment
apiVersion: apps/v1
metadata:
    name: greeting
    namespace: default
    selfLink: /apis/apps/v1/namespaces/default/deployments/greeting
    uid: 6d095139-c380-4f88-a80c-5bdbb5b74925
    resourceVersion: '403397'
    generation: 1
    creationTimestamp: '2020-12-02T07:22:41Z'
    labels:
        app: greeting
    annotations:
        deployment.kubernetes.io/revision: '1'
    managedFields:
        - manager: kube-controller-manager
          operation: Update
          apiVersion: apps/v1
          time: '2020-12-02T07:22:41Z'
          fieldsType: FieldsV1
          fieldsV1:
              'f:metadata':
                  'f:annotations':
                      .: {}
                      'f:deployment.kubernetes.io/revision': {}
              'f:status':
                  'f:conditions':
                      .: {}
                      'k:{"type":"Available"}':
                          .: {}
                          'f:lastTransitionTime': {}
                          'f:lastUpdateTime': {}
                          'f:message': {}
                          'f:reason': {}
                          'f:status': {}
                          'f:type': {}
                      'k:{"type":"Progressing"}':
                          .: {}
                          'f:lastTransitionTime': {}
                          'f:lastUpdateTime': {}
                          'f:message': {}
                          'f:reason': {}
                          'f:status': {}
                          'f:type': {}
                  'f:observedGeneration': {}
                  'f:replicas': {}
                  'f:unavailableReplicas': {}
                  'f:updatedReplicas': {}
        - manager: kubectl-create
          operation: Update
          apiVersion: apps/v1
          time: '2020-12-02T07:22:41Z'
          fieldsType: FieldsV1
          fieldsV1:
              'f:metadata':
                  'f:labels':
                      .: {}
                      'f:app': {}
              'f:spec':
                  'f:progressDeadlineSeconds': {}
                  'f:replicas': {}
                  'f:revisionHistoryLimit': {}
                  'f:selector':
                      'f:matchLabels':
                          .: {}
                          'f:app': {}
                  'f:strategy':
                      'f:rollingUpdate':
                          .: {}
                          'f:maxSurge': {}
                          'f:maxUnavailable': {}
                      'f:type': {}
                  'f:template':
                      'f:metadata':
                          'f:labels':
                              .: {}
                              'f:app': {}
                      'f:spec':
                          'f:containers':
                              'k:{"name":"minikube-greeting-htbhr"}':
                                  .: {}
                                  'f:image': {}
                                  'f:imagePullPolicy': {}
                                  'f:name': {}
                                  'f:resources': {}
                                  'f:terminationMessagePath': {}
                                  'f:terminationMessagePolicy': {}
                          'f:dnsPolicy': {}
                          'f:restartPolicy': {}
                          'f:schedulerName': {}
                          'f:securityContext': {}
                          'f:terminationGracePeriodSeconds': {}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: greeting
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: greeting
        spec:
            containers:
                - name: minikube-greeting-htbhr
                  image: quarkus/minikube_greeting
                  resources: {}
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  imagePullPolicy: IfNotPresent
            restartPolicy: Always
            terminationGracePeriodSeconds: 30
            dnsPolicy: ClusterFirst
            securityContext: {}
            schedulerName: default-scheduler
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 25%
            maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
status:
    observedGeneration: 1
    replicas: 1
    updatedReplicas: 1
    unavailableReplicas: 1
    conditions:
        - type: Available
          status: 'False'
          lastUpdateTime: '2020-12-02T07:22:41Z'
          lastTransitionTime: '2020-12-02T07:22:41Z'
          reason: MinimumReplicasUnavailable
          message: Deployment does not have minimum availability.
        - type: Progressing
          status: 'True'
          lastUpdateTime: '2020-12-02T07:22:41Z'
          lastTransitionTime: '2020-12-02T07:22:41Z'
          reason: ReplicaSetUpdated
          message: ReplicaSet "greeting-67c5444f7f" is progressing.
