kind: Deployment
apiVersion: apps/v1
metadata:
    name: greeting
spec:
    selector:
        matchLabels:
            app: greeting
    replicas: 2

    template:
        metadata:
            creationTimestamp: null
            labels:
                app: greeting
        spec:
            containers:
                - name: minikube-greeting-htbhr
                  image: quarkus/minikube_greeting-jvm:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      -   containerPort: 8080
                  env:
                      -   name: POSTGRES_HOST
                          value: postgres-greeting
                      -   name: POSTGRES_PORT
                          value: "5432"
                      -   name: POSTGRES_DB
                          valueFrom:
                              configMapKeyRef:
                                  key: POSTGRES_DB
                                  name: postgres-greeting-config
                      -   name: POSTGRES_USER
                          valueFrom:
                              configMapKeyRef:
                                  key: POSTGRES_USER
                                  name: postgres-greeting-config
                      -   name: POSTGRES_PASSWORD
                          valueFrom:
                              secretKeyRef:
                                  key: POSTGRES_PASSWORD
                                  name: postgres-greeting-secret
            restartPolicy: Always
            terminationGracePeriodSeconds: 30
            dnsPolicy: ClusterFirst
            securityContext: {}
            schedulerName: default-scheduler
    strategy:
        type: RollingUpdate
#---
#kind: Service
#apiVersion: v1
#metadata:
#    name: greeting
#spec:
#    ports:
#        - protocol: TCP
#          port: 8080
#          targetPort: 8080
#          nodePort: 32026
#    selector:
#        app: greeting
#    clusterIP: 10.102.111.93
#    type: NodePort
#    sessionAffinity: None
#    externalTrafficPolicy: Cluster
---
kind: Service
apiVersion: v1
metadata:
    name: greeting-loadbalancer
spec:
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          nodePort: 32072
    selector:
        app: greeting
    clusterIP: 10.103.13.112
    type: LoadBalancer
    sessionAffinity: None
    externalTrafficPolicy: Cluster